# Generated by Django 5.2.17 on 2026-09-18 18:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_product_id', models.TextField(blank=True, null=True, unique=True)),
                ('name', models.TextField()),
                ('url', models.TextField(unique=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(default='USD')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('currently_in_stock', models.BooleanField(blank=True, null=True)),
                ('scrape_interval_minutes', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('last_successful_scrape_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TrackedProducts',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(default=uuid.uuid4)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('success', 'success'), ('retried', 'retried'), ('failed', 'failed')], max_length=16)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('page_structure_changed', models.BooleanField(default=False)),
                ('headed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='tracker.trackedproduct')),
            ],
            options={
                'db_table': 'ScrapeLogs',
                'ordering': ['-attempted_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.TextField(default='USD')),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrape_log', models.ForeignKey(blank=True, db_column='scrape_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_points', to='tracker.scrapelog')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.trackedproduct')),
            ],
            options={
                'db_table': 'PriceHistory',
                'ordering': ['-scraped_at'],
                'managed': True,
            },
        ),
    ]
